language: python
python:
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"
node_js:
  - "0.12"
before_install:
  - sudo apt-get update && sudo apt-get --reinstall install -qq language-pack-fr
install:
  - npm install jshint
  - pip install coveralls
  - cd python/
  - pip install -r requirements.txt
  - cd ..

script:
  - node_modules/.bin/jshint --exclude public/bower_components public/
  - cd python/
  - nosetests --with-coverage
  - pep8
  - flake8
after_success:
  - coveralls
